### ISSUE TITLE
Handle subscriptions with deleted products

### ISSUE THREAD

**Issue by aldesantis** [solidusio-contrib/solidus_subscriptions#133]
When a product is soft-deleted, it should also be removed from all active subscriptions, or perhaps we shouldn't allow deleting a product that has active subscriptions associated.

**Comment by luca-landa** [comment]
Since we can't assume the subscribable class will always be a subclass of `Spree::Variant`, it may be harder to fix subscriptions on subscribable deletion.
If we want to allow products deletion when they're still included in an active subscriptions, I see two main ways:
* handle the case while processing the subscription, checking for subscribables existence and removing them before processing, if needed
* handle the case in a cleaner way through decoration of the subscribable class.
  * in that case we could apply the decoration only if the class is a `Spree::Variant`, or maybe the restriction could be that it needs to be an `ActiveRecord` model and then hook up the fix on its `after_deletion` or `after_discard` callbacks.

I would rather go for the second option, any opinion?

**Comment by aldesantis** [comment]
@luca-landa thanks for the analysis here! I think removing the variant from any associated subscriptions is the right way to go here. I also think we should only do this when we're dealing with `Spree::Variant`, and just delegate the logic to the user in case they're using a custom subscribable class (which is unlikely, anyway).

**Comment by luca-landa** [comment]
does it make sense to delete the `Spree::Variant` from every subscription? Or should it be removed from active subscriptions only? (what about soft-deleting it from every subscription?)
